name: jiji_safi
description: "Air quality monitoring dashboard with maps and health alerts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.0.0
  google_maps_flutter: ^2.6.1
  location: ^5.0.3
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^4.17.0
  firebase_database: ^10.0.0
  mqtt_client: ^10.2.0   # <-- Add this line for MQTT support

flutter:
  uses-material-design: true
  assets:
    - .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

